---
title: "Weight of Fish"
author: "Teresa Juan"
date: "`r Sys.Date()`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
require(leaps)
```

```{r}
All_Fish <- read.csv(file = "Fish.csv")
```

```{r}
Perch <- filter(All_Fish, Species=="Perch")
```

```{r}
Perch <- select(Perch, -Species)
```

# Predicting Fish Weight

## Perch

```{r}
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = Perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```

### Best Models

best model for Perch is height and width
### Best 

the best two regression models height and width.

## Pike



### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements